server.port=8081
spring.application.name=host-app-example
workflow.engine.enabled=true
workflow.engine.api.enabled=true
workflow.engine.api.base-path=/workflows
workflow.engine.api.insecure-ssl=true
workflow.engine.ui.enabled=true
workflow.engine.ui.path=/workflow-ui
workflow.engine.definition.source=file
workflow.engine.definition.path=host-app-example/configs/workflows
workflow.engine.definition.cache-enabled=true
workflow.engine.execution.max-retries=3
workflow.engine.execution.retry-backoff-ms=2000
workflow.engine.persistence.type=jpa
workflow.engine.security.enabled=false

# Swagger UI: http://localhost:8081/swagger-ui.html  (OpenAPI JSON: /v3/api-docs)
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
