CREATE TABLE IF NOT EXISTS workflows (
    id VARCHAR(120) PRIMARY KEY,
    definition_json CLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS workflow_instances (
    id UUID PRIMARY KEY,
    workflow_id VARCHAR(120) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS workflow_steps (
    id UUID PRIMARY KEY,
    instance_id UUID NOT NULL,
    step_id VARCHAR(120) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS user_tasks (
    id UUID PRIMARY KEY,
    workflow_id VARCHAR(120) NOT NULL,
    step_id VARCHAR(120) NOT NULL,
    status VARCHAR(50) NOT NULL,
    assignment_type VARCHAR(50),
    assignment_value VARCHAR(255),
    claimed_by VARCHAR(120),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS user_task_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    candidate_value VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_task_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id UUID NOT NULL,
    user_id VARCHAR(120) NOT NULL,
    decision VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    CONSTRAINT uk_task_user UNIQUE(task_id, user_id)
);

CREATE TABLE IF NOT EXISTS workflow_audit_events (
    id UUID PRIMARY KEY,
    workflow_id VARCHAR(120) NOT NULL,
    task_id UUID,
    event_type VARCHAR(100) NOT NULL,
    payload VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_tasks_status_assignment ON user_tasks(status, assignment_type, assignment_value);
CREATE INDEX IF NOT EXISTS idx_user_task_candidates_type_value ON user_task_candidates(type, candidate_value);
CREATE INDEX IF NOT EXISTS idx_user_task_approvals_task_user ON user_task_approvals(task_id, user_id);
